import sqlite3


def create_database():
    conn = sqlite3.connect('games.db')
    cursor = conn.cursor()

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS games (
            id INTEGER PRIMARY KEY,
            name TEXT UNIQUE,
            platform TEXT,
            genre TEXT,
            steam_link TEXT,
            gog_link TEXT,
            epic_link TEXT
        )
    ''')


    games = [
        ("The Witcher 3: Wild Hunt", "PC", "RPG", "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
         "https://www.gog.com/game/the_witcher_3_wild_hunt",
         "https://store.epicgames.com/ru/p/the-witcher-3-wild-hunt"),
        ("Cyberpunk 2077", "PC", "RPG", "https://store.steampowered.com/app/1091500/Cyberpunk_2077/",
         "https://www.gog.com/game/cyberpunk_2077", "https://store.epicgames.com/ru/p/cyberpunk-2077"),
        ("Red Dead Redemption 2", "PC", "Action-Adventure",
         "https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/",
         "https://www.gog.com/game/red_dead_redemption_2", "https://store.epicgames.com/ru/p/red-dead-redemption-2"),
        ("Minecraft", "PC", "Sandbox", "https://www.minecraft.net/en-us", None, None),
        (
        "Grand Theft Auto V", "PC", "Action-Adventure", "https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/",
        "https://store.rockstargames.com/en/game/buy-grand-theft-auto-v",
        "https://store.epicgames.com/ru/p/grand-theft-auto-v"),
        ("The Elder Scrolls V: Skyrim", "PC", "RPG",
         "https://store.steampowered.com/app/72850/The_Elder_Scrolls_V_Skyrim/",
         "https://www.gog.com/game/the_elder_scrolls_v_skyrim_anniversary_edition", None),
        ("DOOM Eternal", "PC", "Shooter", "https://store.steampowered.com/app/782330/DOOM_Eternal/",
         "https://www.gog.com/game/doom_eternal", None),
        ("Stardew Valley", "PC", "Simulation", "https://store.steampowered.com/app/413150/Stardew_Valley/",
         "https://www.gog.com/game/stardew_valley", None),
        ("Dark Souls III", "PC", "Action RPG", "https://store.steampowered.com/app/374320/DARK_SOULS_III/",
         "https://www.gog.com/game/dark_souls_iii_the_fire_fades_edition", None),
        ("Sekiro: Shadows Die Twice", "PC", "Action-Adventure",
         "https://store.steampowered.com/app/814380/Sekiro_Shadows_Die_Twice/",
         "https://www.gog.com/game/sekiro_shadows_die_twice_goty_edition", None),
        ("Hollow Knight", "PC", "Metroidvania", "https://store.steampowered.com/app/367520/Hollow_Knight/",
         "https://www.gog.com/game/hollow_knight", "https://store.epicgames.com/ru/p/hollow-knight"),
        ("Celeste", "PC", "Platformer", "https://store.steampowered.com/app/504230/Celeste/",
         "https://www.gog.com/game/celeste", "https://store.epicgames.com/ru/p/celeste"),
        ("Terraria", "PC", "Sandbox", "https://store.steampowered.com/app/105600/Terraria/",
         "https://www.gog.com/game/terraria", None),
        ("Factorio", "PC", "Simulation", "https://store.steampowered.com/app/427520/Factorio/",
         "https://www.gog.com/game/factorio", None),
        ("Cities: Skylines", "PC", "Simulation", "https://store.steampowered.com/app/255710/Cities_Skylines/",
         "https://www.gog.com/game/cities_skylines", "https://store.epicgames.com/ru/p/cities-skylines"),
        ("Crusader Kings III", "PC", "Strategy", "https://store.steampowered.com/app/1158310/Crusader_Kings_III/",
         "https://www.gog.com/game/crusader_kings_iii", None),
        ("Europa Universalis IV", "PC", "Strategy", "https://store.steampowered.com/app/236850/Europa_Universalis_IV/",
         "https://www.gog.com/game/europa_universalis_iv", None),
        ("Civilization VI", "PC", "Strategy", "https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/",
         "https://www.gog.com/game/sid_meiers_civilization_vi_platinum_edition",
         'https://store.epicgames.com/ru/p/sid-meiers-civilization-vi'),
        ("Portal 2", "PC", "Puzzle", "https://store.steampowered.com/app/620/Portal_2/",
         "https://www.gog.com/game/portal_2", None),
        ("The Legend of Zelda: Breath of the Wild", "Nintendo Switch", "Action-Adventure", None, None, None),
        ("Super Mario Odyssey", "Nintendo Switch", "Platformer", None, None, None),
        ("Animal Crossing: New Horizons", "Nintendo Switch", "Simulation", None, None, None),
        ("The Last of Us Part II", "PlayStation", "Action-Adventure", None, None, None),
        (
        "God of War", "PlayStation", "Action-Adventure", "https://store.steampowered.com/app/1593500/God_of_War/", None,
        "https://store.epicgames.com/ru/p/god-of-war"),
        ("Uncharted 4: A Thief's End", "PlayStation", "Action-Adventure", None, None, None),
        ("Spider-Man", "PlayStation", "Action-Adventure",
         "https://store.steampowered.com/app/1817070/Marvels_SpiderMan_Remastered/", None,
         "https://store.epicgames.com/ru/p/marvels-spider-man-remastered"),
        ("Star Wars Jedi: Fallen Order", "PC", "Action-Adventure",
         "https://store.steampowered.com/app/1172380/STAR_WARS_Jedi_Fallen_Order/",
         "https://www.gog.com/game/star_wars_jedi_fallen_order",
         "https://store.epicgames.com/ru/p/star-wars-jedi-fallen-order"),
        ("The Outer Worlds", "PC", "RPG", "https://store.steampowered.com/app/578650/The_Outer_Worlds/",
         "https://www.gog.com/game/the_outer_worlds", "https://store.epicgames.com/ru/p/the-outer-worlds"),
        ("Disco Elysium", "PC", "RPG", "https://store.steampowered.com/app/632470/Disco_Elysium__The_Final_Cut/",
         "https://www.gog.com/game/disco_elysium", "https://store.epicgames.com/ru/p/disco-elysium"),
        ("Divinity: Original Sin 2", "PC", "RPG", "https://store.steampowered.com/app/435150/Divinity_Original_Sin_2/",
         "https://www.gog.com/game/divinity_original_sin_2", None),
        ("Mass Effect Legendary Edition", "PC", "RPG",
         "https://store.steampowered.com/app/1328670/Mass_Effect_Legendary_Edition/",
         "https://www.gog.com/game/mass_effect_legendary_edition",
         "https://store.epicgames.com/ru/p/mass-effect-legendary-edition"),
        ("Fallout 4", "PC", "RPG", "https://store.steampowered.com/app/377160/Fallout_4/",
         "https://www.gog.com/game/fallout_4", None),
        ("Subnautica", "PC", "Survival", "https://store.steampowered.com/app/264710/Subnautica/",
         "https://www.gog.com/game/subnautica", "https://store.epicgames.com/ru/p/subnautica"),
        ("The Forest", "PC", "Survival", "https://store.steampowered.com/app/242760/The_Forest/", None, None),
        ("Rust", "PC", "Survival", "https://store.steampowered.com/app/252490/Rust/", None, None),
        ("ARK: Survival Evolved", "PC", "Survival", "https://store.steampowered.com/app/346110/ARK_Survival_Evolved/",
         "https://www.gog.com/game/ark_survival_evolved", "https://store.epicgames.com/ru/p/ark"),
        ("No Man's Sky", "PC", "Survival", "https://store.steampowered.com/app/275850/No_Mans_Sky/",
         "https://www.gog.com/game/no_mans_sky", "https://store.epicgames.com/ru/p/no-mans-sky"),
        ("Half-Life: Alyx", "PC", "VR", "https://store.steampowered.com/app/546560/HalfLife_Alyx/", None, None),
        ("Beat Saber", "PC", "VR", "https://store.steampowered.com/app/620980/Beat_Saber/", None, None),
        ("Microsoft Flight Simulator", "PC", "Simulation",
         "https://store.steampowered.com/app/1250410/Microsoft_Flight_Simulator/", None,
         "https://store.epicgames.com/ru/p/microsoft-flight-simulator"),
        ("Planet Zoo", "PC", "Simulation", "https://store.steampowered.com/app/703080/Planet_Zoo/",
         "https://www.gog.com/game/planet_zoo", None),
        ("Jurassic World Evolution 2", "PC", "Simulation",
         "https://store.steampowered.com/app/1244460/Jurassic_World_Evolution_2/", None,
         "https://store.epicgames.com/ru/p/jurassic-world-evolution-2"),
        ("Age of Empires IV", "PC", "Strategy", "https://store.steampowered.com/app/1466860/Age_of_Empires_IV/", None,
         "https://store.epicgames.com/ru/p/age-of-empires-iv"),
        ("Total War: Warhammer III", "PC", "Strategy",
         "https://store.steampowered.com/app/1142710/Total_War_WARHAMMER_III/", None,
         "https://store.epicgames.com/ru/p/total-war-warhammer-iii"),
        ("XCOM 2", "PC", "Strategy", "https://store.steampowered.com/app/268500/XCOM_2/",
         "https://www.gog.com/game/xcom_2", "https://store.epicgames.com/ru/p/xcom-2"),
        ("Battlefield 2042", "PC", "Shooter", "https://store.steampowered.com/app/1517260/Battlefield_2042/", None,
         "https://store.epicgames.com/ru/p/battlefield-2042"),
        ("Call of Duty: Warzone", "PC", "Shooter", None, None, None),
        ("Overwatch 2", "PC", "Shooter", "https://store.steampowered.com/app/2357570/Overwatch_2/", None,
         "https://store.epicgames.com/ru/p/overwatch-2"),
        ("Rainbow Six Siege", "PC", "Shooter",
         "https://store.steampowered.com/app/359550/Tom_Clancys_Rainbow_Six_Siege/",
         "https://www.gog.com/game/tom_clancys_rainbow_six_siege", None),
        ("Apex Legends", "PC", "Shooter", "https://store.steampowered.com/app/1172470/Apex_Legends/", None, None),
        ("Rocket League", "PC", "Sports", "https://store.steampowered.com/app/252950/Rocket_League/",
         "https://www.gog.com/game/rocket_league", "https://store.epicgames.com/ru/p/rocket-league"),
        ("FIFA 23", "PC", "Sports", "https://store.steampowered.com/app/1811260/FIFA_23/", None,
         "https://store.epicgames.com/ru/p/fifa-23"),
        ("NBA 2K23", "PC", "Sports", "https://store.steampowered.com/app/1919510/NBA_2K23/", None, None),
        ("Forza Horizon 5", "PC", "Racing", "https://store.steampowered.com/app/1551360/Forza_Horizon_5/", None, None),
        ("Gran Turismo 7", "PlayStation", "Racing", None, None, None),
        ("Death Stranding", "PC", "Action", "https://store.steampowered.com/app/1190460/DEATH_STRANDING_DIRECTORS_CUT/",
         "https://www.gog.com/game/death_stranding_directors_cut", "https://store.epicgames.com/ru/p/death-stranding"),
        ("Control", "PC", "Action", "https://store.steampowered.com/app/870780/Control_Ultimate_Edition/",
         "https://www.gog.com/game/control_ultimate_edition", "https://store.epicgames.com/ru/p/control"),
        ("Resident Evil Village", "PC", "Horror", "https://store.steampowered.com/app/1196590/Resident_Evil_Village/",
         "https://www.gog.com/game/resident_evil_village", "https://store.epicgames.com/ru/p/resident-evil-village"),
        ("Outlast", "PC", "Horror", "https://store.steampowered.com/app/238320/Outlast/",
         "https://www.gog.com/game/outlast", "https://store.epicgames.com/ru/p/outlast"),
        ("Little Nightmares II", "PC", "Horror", "https://store.steampowered.com/app/860510/Little_Nightmares_II/",
         "https://www.gog.com/game/little_nightmares_ii", "https://store.epicgames.com/ru/p/little-nightmares-ii"),
        ("Cuphead", "PC", "Platformer", "https://store.steampowered.com/app/268910/Cuphead/",
         "https://www.gog.com/game/cuphead", "https://store.epicgames.com/ru/p/cuphead"),
        ("Ori and the Will of the Wisps", "PC", "Platformer",
         "https://store.steampowered.com/app/1057090/Ori_and_the_Will_of_the_Wisps/",
         "https://www.gog.com/game/ori_and_the_will_of_the_wisps",
         "https://store.epicgames.com/ru/p/ori-and-the-will-of-the-wisps"),
        ("It Takes Two", "PC", "Co-op", "https://store.steampowered.com/app/1426210/It_Takes_Two/",
         "https://www.gog.com/game/it_takes_two", "https://store.epicgames.com/ru/p/it-takes-two"),
        ("A Way Out", "PC", "Co-op", "https://store.steampowered.com/app/502300/A_Way_Out/",
         "https://www.gog.com/game/a_way_out", "https://store.epicgames.com/ru/p/a-way-out"),
        ("Among Us", "PC", "Multiplayer", "https://store.steampowered.com/app/945360/Among_Us/",
         "https://www.gog.com/game/among_us", "https://store.epicgames.com/ru/p/among-us"),
        ("Fall Guys", "PC", "Multiplayer", "https://store.steampowered.com/app/1097150/Fall_Guys_Ultimate_Knockout/",
         None, "https://store.epicgames.com/ru/p/fall-guys"),
        ("League of Legends", "PC", "MOBA", None, None, None),
        ("Dota 2", "PC", "MOBA", "https://store.steampowered.com/app/570/Dota_2/", None, None),
        ("Warcraft III Reforged", "PC", "RTS", "https://us.shop.battle.net/en-us/product/warcraft-iii-reforged", None,
         None),
        ("StarCraft II", "PC", "RTS", "https://starcraft2.com/en-us/", None, None),
        ("Gears 5", "PC", "Shooter", "https://store.steampowered.com/app/1097840/Gears_5/", None, None),
        ("Wolfenstein II: The New Colossus", "PC", "Shooter",
         "https://store.steampowered.com/app/612810/Wolfenstein_II_The_New_Colossus/",
         "https://www.gog.com/game/wolfenstein_ii_the_new_colossus",
         "https://store.epicgames.com/ru/p/wolfenstein-ii-the-new-colossus"),
        ("Far Cry 6", "PC", "Shooter", "https://store.steampowered.com/app/2367650/Far_Cry_6/",
         "https://www.gog.com/game/far_cry_6", "https://store.epicgames.com/ru/p/far-cry-6"),
        ("Borderlands 3", "PC", "Shooter", "https://store.steampowered.com/app/397540/Borderlands_3/",
         "https://www.gog.com/game/borderlands_3", "https://store.epicgames.com/ru/p/borderlands-3"),
        ("Metro Exodus", "PC", "Shooter", "https://store.steampowered.com/app/412020/Metro_Exodus/",
         "https://www.gog.com/game/metro_exodus", "https://store.epicgames.com/ru/p/metro-exodus"),
        ("The Sims 4", "PC", "Simulation", "https://store.steampowered.com/app/1222670/The_Sims_4/", None, None),
        ("Kerbal Space Program", "PC", "Simulation", "https://store.steampowered.com/app/220200/Kerbal_Space_Program/",
         "https://www.gog.com/game/kerbal_space_program", None),
        ("Two Point Hospital", "PC", "Simulation", "https://store.steampowered.com/app/535930/Two_Point_Hospital/",
         "https://www.gog.com/game/two_point_hospital", "https://store.epicgames.com/ru/p/two-point-hospital"),
        ("Prison Architect", "PC", "Simulation", "https://store.steampowered.com/app/233450/Prison_Architect/",
         "https://www.gog.com/game/prison_architect", None),
        ("Anno 1800", "PC", "Simulation", "https://store.steampowered.com/app/916440/Anno_1800/",
         "https://www.gog.com/game/anno_1800", "https://store.epicgames.com/ru/p/anno-1800"),
        ("Slay the Spire", "PC", "Card Game", "https://store.steampowered.com/app/646570/Slay_the_Spire/",
         "https://www.gog.com/game/slay_the_spire", "https://store.epicgames.com/ru/p/slay-the-spire"),
        ("Monster Train", "PC", "Card Game", "https://store.steampowered.com/app/1102190/Monster_Train/",
         "https://www.gog.com/game/monster_train", "https://store.epicgames.com/ru/p/monster-train"),
        ("Baba Is You", "PC", "Puzzle", "https://store.steampowered.com/app/736260/Baba_Is_You/",
         "https://www.gog.com/game/baba_is_you", "https://store.epicgames.com/ru/p/baba-is-you"),
        ("The Witness", "PC", "Puzzle", "https://store.steampowered.com/app/210970/The_Witness/",
         "https://www.gog.com/game/the_witness", None),
        ("Super Meat Boy", "PC", "Platformer", "https://store.steampowered.com/app/40800/Super_Meat_Boy/",
         "https://www.gog.com/game/super_meat_boy", "https://store.epicgames.com/ru/p/super-meat-boy"),
        ("Limbo", "PC", "Platformer", "https://store.steampowered.com/app/48000/LIMBO/",
         "https://www.gog.com/game/limbo", "https://store.epicgames.com/ru/p/limbo"),
        ("Inside", "PC", "Platformer", "https://store.steampowered.com/app/304430/INSIDE/",
         "https://www.gog.com/game/inside", "https://store.epicgames.com/ru/p/inside"),
        ("Pathfinder: Wrath of the Righteous", "PC", "RPG",
         "https://store.steampowered.com/app/1183460/Pathfinder_Wrath_of_the_Righteous/",
         "https://www.gog.com/game/pathfinder_wrath_of_the_righteous",
         "https://store.epicgames.com/ru/p/pathfinder-wrath-of-the-righteous"),
        ("Baldur's Gate 3", "PC", "RPG", "https://store.steampowered.com/app/1086940/Baldurs_Gate_3/",
         "https://www.gog.com/game/baldurs_gate_iii", None),
        ("Darkest Dungeon", "PC", "RPG", "https://store.steampowered.com/app/262060/Darkest_Dungeon/",
         "https://www.gog.com/game/darkest_dungeon", "https://store.epicgames.com/ru/p/darkest-dungeon"),
        ("Pillars of Eternity II: Deadfire", "PC", "RPG",
         "https://store.steampowered.com/app/560130/Pillars_of_Eternity_II_Deadfire/",
         "https://www.gog.com/game/pillars_of_eternity_ii_deadfire",
         "https://store.epicgames.com/ru/p/pillars-of-eternity-ii-deadfire"),
        (
        "Doom 3", "PC", "Shooter", "https://store.steampowered.com/app/9050/DOOM_3/", "https://www.gog.com/game/doom_3",
        None),
        ("Quake", "PC", "Shooter", "https://store.steampowered.com/app/2310/QUAKE/",
         "https://www.gog.com/game/quake_the_offering", "https://store.epicgames.com/ru/p/quake"),
        ("Bioshock", "PC", "Shooter", "https://store.steampowered.com/app/7670/BioShock/",
         "https://www.gog.com/game/bioshock", None),
        ("Prey", "PC", "Shooter", "https://store.steampowered.com/app/480490/Prey/", "https://www.gog.com/game/prey",
         "https://store.epicgames.com/ru/p/prey"),
        ("System Shock 2", "PC", "Shooter", "https://store.steampowered.com/app/238210/System_Shock_2/",
         "https://www.gog.com/game/system_shock_2", None),
        ("Dishonored", "PC", "Action", "https://store.steampowered.com/app/205100/Dishonored/",
         "https://www.gog.com/game/dishonored", "https://store.epicgames.com/ru/p/dishonored"),
        ("Deathloop", "PC", "Action", "https://store.steampowered.com/app/1252330/DEATHLOOP/", None,
         "https://store.epicgames.com/ru/p/deathloop"),
        ("Elden Ring", "PC", "Action RPG", "https://store.steampowered.com/app/1245620/ELDEN_RING/",
         "https://www.gog.com/game/elden_ring", "https://store.epicgames.com/ru/p/elden-ring"),
        ("Nioh 2", "PC", "Action RPG", "https://store.steampowered.com/app/1325200/Nioh_2__The_Complete_Edition/",
         "https://www.gog.com/game/nioh_2_the_complete_edition", "https://store.epicgames.com/ru/p/nioh-2"),
        ("Code Vein", "PC", "Action RPG", "https://store.steampowered.com/app/678960/CODE_VEIN/",
         "https://www.gog.com/game/code_vein", "https://store.epicgames.com/ru/p/code-vein"),
        ("Monster Hunter World", "PC", "Action RPG", "https://store.steampowered.com/app/582010/Monster_Hunter_World/",
         "https://www.gog.com/game/monster_hunter_world", "https://store.epicgames.com/ru/p/monster-hunter-world"),
        ("Star Wars Battlefront II", "PC", "Shooter",
         "https://store.steampowered.com/app/1237950/STAR_WARS_Battlefront_II/", None,
         "https://store.epicgames.com/ru/p/star-wars-battlefront-ii"),
        ("Titanfall 2", "PC", "Shooter", "https://store.steampowered.com/app/1237970/Titanfall_2/", None,
         "https://store.epicgames.com/ru/p/titanfall-2"),
        ("Team Fortress 2", "PC", "Shooter", "https://store.steampowered.com/app/440/Team_Fortress_2/", None, None),
        ("Counter-Strike: Global Offensive", "PC", "Shooter",
         "https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/", None, None),
        ("Left 4 Dead 2", "PC", "Shooter", "https://store.steampowered.com/app/550/Left_4_Dead_2/",
         "https://www.gog.com/game/left_4_dead_2", None),
        ("Dead Cells", "PC", "Roguelike", "https://store.steampowered.com/app/588650/Dead_Cells/",
         "https://www.gog.com/game/dead_cells", "https://store.epicgames.com/ru/p/dead-cells"),
        ("Enter the Gungeon", "PC", "Roguelike", "https://store.steampowered.com/app/311690/Enter_the_Gungeon/",
         "https://www.gog.com/game/enter_the_gungeon", "https://store.epicgames.com/ru/p/enter-the-gungeon"),
        ("Hades", "PC", "Roguelike", "https://store.steampowered.com/app/1145360/Hades/",
         "https://www.gog.com/game/hades", "https://store.epicgames.com/ru/p/hades"),
        ("Risk of Rain 2", "PC", "Roguelike", "https://store.steampowered.com/app/632360/Risk_of_Rain_2/",
         "https://www.gog.com/game/risk_of_rain_2", "https://store.epicgames.com/ru/p/risk-of-rain-2"),
        ("The Binding of Isaac: Rebirth", "PC", "Roguelike",
         "https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/",
         "https://www.gog.com/game/the_binding_of_isaac_rebirth", None),
        ("Divinity: Original Sin", "PC", "RPG",
         "https://store.steampowered.com/app/373420/Divinity_Original_Sin_Enhanced_Edition/",
         "https://www.gog.com/game/divinity_original_sin_enhanced_edition", None),
        ("Tyranny", "PC", "RPG", "https://store.steampowered.com/app/362960/Tyranny/",
         "https://www.gog.com/game/tyranny", None),
        ("The Witcher 2: Assassins of Kings", "PC", "RPG",
         "https://store.steampowered.com/app/20920/The_Witcher_2_Assassins_of_Kings_Enhanced_Edition/",
         "https://www.gog.com/game/the_witcher_2", None),
        ("Dragon Age: Origins", "PC", "RPG",
         "https://store.steampowered.com/app/17450/Dragon_Age_Origins__Ultimate_Edition/",
         "https://www.gog.com/game/dragon_age_origins_ultimate_edition", None),
        ("Pillars of Eternity", "PC", "RPG", "https://store.steampowered.com/app/291650/Pillars_of_Eternity/",
         "https://www.gog.com/game/pillars_of_eternity", None),
        ("Star Wars: Knights of the Old Republic", "PC", "RPG",
         "https://store.steampowered.com/app/32370/STAR_WARS__Knights_of_the_Old_Republic/",
         "https://www.gog.com/game/star_wars_knights_of_the_old_republic", None),
        ("Warframe", "PC", "Action", "https://store.steampowered.com/app/230410/Warframe/", None, None),
        ("Path of Exile", "PC", "Action RPG", "https://store.steampowered.com/app/238960/Path_of_Exile/", None, None)
    ]

    for game in games:
        try:
            cursor.execute(
                "INSERT INTO games (name, platform, genre, steam_link, gog_link, epic_link) VALUES (?, ?, ?, ?, ?, ?)",
                game)
        except sqlite3.IntegrityError:
            pass

    conn.commit()
    conn.close()


if __name__ == '__main__':
    create_database()
    print("Database created and populated")